services:
  image-classifier:
    build: .
    container_name: image_classifier
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_SERVICE_CLIENT_ID=${KEYCLOAK_SERVICE_CLIENT_ID}
      - KEYCLOAK_SERVICE_CLIENT_SECRET=${KEYCLOAK_SERVICE_CLIENT_SECRET}
      - FILE_SERVICE_TAGS_URL=${FILE_SERVICE_TAGS_URL}

      # Tells the Google library to look at the path where we mounted the config
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      # Mount the gcloud config folder from your host (Mac/Linux path)
      # For Windows, use: - ${APPDATA}/gcloud:/root/.config/gcloud:ro
      - ~/.config/gcloud:/root/.config/gcloud:ro
    restart: "no" #unless-stopped #CHAGE THIS