services:
  image-classifier:
    build: .
    container_name: image_classifier
    ports:
      - "8081:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - FILE_SERVICE_URL=${FILE_SERVICE_URL}
    restart: "no" #unless-stopped #CHAGE THIS