apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  annotations:
    cloud.google.com/backend-config: '{"default": "image-classification-backend-config"}'
spec:
  selector:
    app: {{ .Values.service.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          ports:
            - containerPort: {{ .Values.deployment.image.containerPort }}
          env:
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.url }}

            - name: KEYCLOAK_REALM_NAME
              value: {{ .Values.keycloak.realm }}

            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.clientId }}

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name}}
                  key: {{ .Values.secrets.keycloakClientSecret}}

            - name: FILE_SERVICE_URL
              value: {{ .Values.fileServiceUrl }}

          # health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2
